name: "Build"

on:
  push:
    branches: [master]
    tags: ["*"]
  pull_request:
    # The branches below must be a subset of the branches above
    branches: [master]
  schedule:
    - cron: '43 16 * * 5'

jobs:
  build-x64:
    name: Build x86-64
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        # https://github.com/actions/checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683
        with:
          fetch-depth: 0

      - name: Set up Python
        # https://github.com/actions/setup-python
        uses: actions/setup-python@0b93645e9fea7318ecaed2b359559ac225c90a2b
        with:
          cache: 'pip'
          architecture: 'x64'
          python-version: '3.*'

      - name: Install dependencies
        shell: cmd
        run: pip install --upgrade -r requirements.txt

      - name: Run tests
        shell: cmd
        run: pytest -v

      - name: Build executable
        shell: cmd
        run: pyinstaller --onefile --distpath=. --workpath=build --version-file=events2dolphin.version events2dolphin.py

      - name: Save executable as artifact
        # https://github.com/actions/upload-artifact
        uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02
        with:
          name: events2dolphin.exe
          path: events2dolphin.exe
          if-no-files-found: error

  build-x86:
    name: Build x86
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        # https://github.com/actions/checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683
        with:
          fetch-depth: 0

      - name: Set up Python
        # https://github.com/actions/setup-python
        uses: actions/setup-python@0b93645e9fea7318ecaed2b359559ac225c90a2b
        with:
          #cache: 'pip'
          architecture: 'x86'
          # Python 3.4 is the last for WinXP
          # Pythin 3.8 is the last for Win7
          python-version: '3.8'

      - name: Install dependencies
        shell: cmd
        run: |
          pip install wheel
          pip install --upgrade -r requirements-x86.txt

      - name: Build executable
        shell: cmd
        run: pyinstaller --onefile --distpath=. --workpath=build --version-file=events2dolphin.version --name=events2dolphin-x86 events2dolphin.py

      - name: Save executable as artifact
        # https://github.com/actions/upload-artifact
        uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02
        with:
          name: events2dolphin-x86.exe
          path: events2dolphin-x86.exe
          if-no-files-found: error

  release:
    name: Publish release
    if: startsWith(github.ref, 'refs/tags/v')
    needs: [build-x86, build-x64]
    runs-on: windows-latest

    steps:
      - name: Download x86 executable as artifact
        # https://github.com/actions/download-artifact
        uses: actions/download-artifact@d3f86a106a0bac45b974a628896c90dbdf5c8093 
        with:
          name: events2dolphin-x86.exe

      - name: Download x64 executable as artifact
        # https://github.com/actions/download-artifact
        uses: actions/download-artifact@d3f86a106a0bac45b974a628896c90dbdf5c8093 
        with:
          name: events2dolphin.exe

      - name: Publish release
        if: startsWith(github.ref, 'refs/tags/v')
        # https://github.com/softprops/action-gh-release
        uses: softprops/action-gh-release@e7a8f85e1c67a31e6ed99a94b41bd0b71bbee6b8
        with:
          draft: true
          files: |
            events2dolphin-x86.exe
            events2dolphin.exe
